# application-dev.properties
# Development configuration for the Inventarisierungsmodul application

# activates security logging
logging.level.org.springframework.security=DEBUG

# activates Error logging
server.error.include-message=always

# activates SQL logging
spring.jpa.show-sql=true

# CORS configuration
allowed.origin=http://localhost:4200
